name: publish-test-m1
on: [push]
jobs:
  publish-hello-world-image-m1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image
        run: |
          docker build . --tag ghcr.io/nevermindeverlong/wildfly17jdk8-m1:latest -f wildfly17jdk8-M1
          docker push ghcr.io/nevermindeverlong/wildfly17jdk8-m1:latest
