name: publish-test
on:
  #push:
  workflow_dispatch:
  schedule:
    - cron: "1 0 1,10,20 * *"
jobs:
  publish-hello-world-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build the Docker image
        run: |
          docker build . --tag ghcr.io/nevermindeverlong/wildfly17jdk8:latest -f wildfly17jdk8
          docker push ghcr.io/nevermindeverlong/wildfly17jdk8:latest
