name: publish-wildfly26_1_3jdk11-temurin
on:
  #push:
  workflow_dispatch:
  schedule:
    - cron: "1 0 1,10,20 * *"
jobs:
  wildfly26_1_3jdk11-temurin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      # Debug
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push eclipse temurin11 alpine
        uses: docker/build-push-action@v4
        with:
          context: .
          file: wildfly26_1_3jdk11-temurin
          platforms: linux/amd64
          push: true
          tags: ghcr.io/nevermindeverlong/wildfly26_1_3jdk11-temurin:latest
